### ISSUE TITLE
returned ball for unknown reason

### ISSUE THREAD

**Issue by KazzaRazza** [jaylawl/Jaygrounds#2] opened 2021-09-25 22:17 UTC
Several times when trying to hit the ball i will get a message saying "returned ball for unknown reason" and it will count the strike against me as a stroke.
One other thing I have encountered for the first time is several times when going to hit the ball it acts like I am double clicking although I am not and will will tack on an extra couple strokes that I had not done and that did not start until today, so sometimes when only trying to hit the ball once it will act as though I hit it two or three times and this happened on feather farms

**Comment by jaylawl** [comment] 2021-09-25 22:25
```Several times when trying to hit the ball i will get a message saying "returned ball for unknown reason" and it will count the strike against me as a stroke.```
This is inprecise, when *exactly* is this happening?

```One other thing I have encountered for the first time is several times when going to hit the ball it acts like I am double clicking although I am not and will will tack on an extra couple strokes that I had not done and that did not start until today, so sometimes when only trying to hit the ball once it will act as though I hit it two or three times and this happened on feather farms```
That usually cannot occur because balls ignore being struck if they are already moving. I would have to know how to reproduce this

In the future, please make seperated posts for each issue - as these are two different ones that you posted

**Comment by TheMysterys** [comment] 2021-09-25 22:42
> Several times when trying to hit the ball I will get a message saying "returned ball for unknown reason" and it will count the strike against me as a stroke.

Most common time this happens in when the ball ends back up on the tee when teeing off

**Comment by jaylawl** [comment] 2021-09-25 23:07
> 
> 
> > Several times when trying to hit the ball I will get a message saying "returned ball for unknown reason" and it will count the strike against me as a stroke.
> 
> Most common time this happens in when the ball ends back up on the tee when teeing off

That was my first thought too, but she said it happens in the moment she hits the ball

**Comment by KazzaRazza** [comment] 2021-09-26 02:38
It happened without the ball ever leaving the the tee, I go to hit the ball for the first time and i will get that message so not sure how that is invalid on my behalf lol

**Comment by jaylawl** [comment] 2021-09-26 09:32
> 
> 
> It happened without the ball ever leaving the tee, I go to hit the ball for the first time and i will get that message so not sure how that is invalid on my behalf lol
> I will see if I can record it

Because i need a way to reproduce the issue. If you could record what is happening that would be dope

**Comment by jaylawl** [comment] 2021-10-04 08:59
Re-interpreting issue as "'Ball returned for unknown reason' message is displayed when ball is landing on a tee"

Fixed in dev

**Closed by jaylawl** 2021-10-04 08:59 UTC
Labels: bug, accepted
